#!/bin/sh

# helper script as workaround to make argo-cd supports kustomize3 plugin

FLAGS=""
# Bourne shell only supports =
if [ "$1" = "build" ]; then
    FLAGS="--enable_alpha_plugins"
fi

/usr/local/bin/kustomize3 $@ $FLAGS
